src/web/AppInstaller/protected/controllers/AplicacionController.php
<?php

class AplicacionController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update','view','index','admin','delete'),
				'users'=>array('developer@sisu.mx'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
                $model = $this->loadModel($id);
                
                if(isset($_POST['Usuarios'])){
                    $model->usuarios = Usuario::model()->findAllByPk($_POST['Usuarios']);
                    $model->saveWithRelated('usuarios');
                }
            
		$this->render('view',array(
			'model'=>$model,
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model = new Aplicacion;
                $version = new Version;
                $model->versiones = $version;

		// Uncomment the following line if AJAX validation is needed
		$this->performAjaxValidation(array($model, $version));

		if(isset($_POST['Aplicacion']))
		{
			$model->attributes=$_POST['Aplicacion'];
                        $version->attributes=$_POST['Version'];
                        date_default_timezone_set("America/Mexico_City"); 
                        $version->fecha_version=date('Y-m-d H:i:s');
                        $model->versiones = $version;
                        $model->usuarios = Usuario::model()->findAllByPk($_POST['Usuarios']);
			if($model->saveWithRelated(array('usuarios')))
                        {
                            date_default_timezone_set("America/Mexico_City"); 
                            $version->fecha_version = date('Y-m-d H:i:s');
                            $version->aplicacion_id = $model->id;
                            $version->save();
                            $root = Yii::getPathOfAlias('webroot').Yii::getPathOfAlias('files').'/';
                            if(!file_exists($root.$model->nombre_app))
                            {
                                mkdir($root.$model->nombre_app);  
                            }
                            $file = CUploadedFile::getInstance($model,'img');
                            if (is_object($file) && get_class($file)==='CUploadedFile')
                            {
                                    $file->saveAs($root.$model->nombre_app.'/img.'.$file->getExtensionName());      
                            }
                            
                            if(!file_exists($root.$model->nombre_app.'/'.$version->version))
                            {
                                mkdir($root.$model->nombre_app.'/'.$version->version);  
                            }
                            $fileAPK = CUploadedFile::getInstance($version,'apk');
                            if (is_object($fileAPK) && get_class($fileAPK)==='CUploadedFile')
                            {
                                $fileAPK->saveAs($root.$model->nombre_app.'/'.$version->version.'/'.$model->nombre_app.'.apk');      
                            }
                            $fileIPA = CUploadedFile::getInstance($version,'ipa');
                            if (is_object($fileIPA) && get_class($fileIPA)==='CUploadedFile')
                            {
                                $fileIPA->saveAs($root.$model->nombre_app.'/'.$version->version.'/'.$model->nombre_app.'.ipa');      
                            }
                            $filePLIST = CUploadedFile::getInstance($version,'plist');
                            if (is_object($filePLIST) && get_class($filePLIST)==='CUploadedFile')
                            {
                                $filePLIST->saveAs($root.$model->nombre_app.'/'.$version->version.'/'.$model->nombre_app.'.plist');      
                            }
                            $push = new PushNotificationManager();
                            $push->sendPushForApp("Primera version de ".$model->nombre." esta lista!",$model);
                            $this->redirect(array('view','id'=>$model->id));
                        }
		}

		$this->render('create',array(
			'model'=>$model,
                        'version'=>$version,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
            
                
		$model=$this->loadModel($id);
		// Uncomment the following line if AJAX validation is needed
		$this->performAjaxValidation($model);

		if(isset($_POST['Aplicacion']))
		{
			$model->attributes=$_POST['Aplicacion'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
            
		$model = $this->loadModel($id);
                
                $root = Yii::getPathOfAlias('webroot').Yii::getPathOfAlias('files').'/';
                $dir = $root.$model->nombre_app;
                
                $model->delete();
                
                if(file_exists($dir))
                {
                    function rrmdir($dir) 
                    { 
                      foreach(glob($dir . '/*') as $file) 
                      { 
                        if(is_dir($file)) rrmdir($file); else unlink($file); 
                      } rmdir($dir); 
                    }
                    rrmdir($dir);
                }

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$this->redirect(array('admin'));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Aplicacion('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Aplicacion']))
			$model->attributes=$_GET['Aplicacion'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Aplicacion the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Aplicacion::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Aplicacion $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='aplicacion-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

src/web/AppInstaller/protected/controllers/UsuarioController.php
<?php

class UsuarioController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update','index','view','createMany','admin','delete'),
				'users'=>array('developer@sisu.mx'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
            
                $model = $this->loadModel($id);
                
                if(isset($_POST['Aplicaciones'])){
                    $model->aplicaciones = Aplicacion::model()->findAllByPk($_POST['Aplicaciones']);
                    $model->saveWithRelated('aplicaciones');
                }
                
		$this->render('view',array(
			'model'=>$model,
		));
	}
        
        /**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreateMany()
	{
		Yii::import('MultiModelForm');
 
                //$model = new UserGroup;
                //$model->title = 'Many';

                $member = new Usuario;
                $validatedMembers = array();  //ensure an empty array
                
                if(isset($_POST['Usuario']))
                {

                    if( //validate detail 
                        MultiModelForm::validate($member,$validatedMembers,$deleteItems)
                       )
                       {
                            foreach($validatedMembers as $usr){
                                            $usr->onBeforeSave();
                                    }
                         if (MultiModelForm::save($member,$validatedMembers,$deleteMembers,$masterValues)){
                                if(isset($_POST['Aplicaciones'])){
                                    $apps = Aplicacion::model()->findAllByPk($_POST['Aplicaciones']);
                                    foreach($validatedMembers as $usr){
                                            $usr->aplicaciones = $apps;
                                            $usr->saveWithRelated('aplicaciones');
                                    }
                                }
                                $this->redirect(array('admin'));
                            }
                        }
                }

                $this->render('createMany',array(
                    //'model'=>$model,
                    //submit the member and validatedItems to the widget in the edit form
                    'member'=>$member,
                    'validatedMembers' => $validatedMembers,
                ));

	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Usuario']))
		{
			$model->attributes=$_POST['Usuario'];
                        $model->onBeforeSave();
                        if(isset($_POST['Aplicaciones'])){
                            $model->aplicaciones = Aplicacion::model()->findAllByPk($_POST['Aplicaciones']);
                            $model->saveWithRelated('aplicaciones');
                        }
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$this->redirect(array('admin'));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Usuario('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Usuario']))
			$model->attributes=$_GET['Usuario'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Usuario the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Usuario::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Usuario $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='usuario-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

src/web/AppInstaller/protected/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

src/web/AppInstaller/protected/views/layouts/column2.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div class="span-19">
	<div id="content">
		<?php echo $content; ?>
	</div><!-- content -->
</div>
<div class="span-5 last">
	<div id="sidebar">
	<?php
		$this->beginWidget('zii.widgets.CPortlet', array(
			'title'=>'Operations',
		));
		$this->widget('zii.widgets.CMenu', array(
			'items'=>$this->menu,
			'htmlOptions'=>array('class'=>'operations'),
		));
		$this->endWidget();
	?>
	</div><!-- sidebar -->
</div>
<?php $this->endContent(); ?>

src/web/AppInstaller/protected/views/layouts/main.php
<?php /* @var $this Controller */ ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="language" content="en" />

	<!-- blueprint CSS framework -->
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/screen.css" media="screen, projection" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/print.css" media="print" />
	<!--[if lt IE 8]>
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/ie.css" media="screen, projection" />
	<![endif]-->

	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/main.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/form.css" />

	<title><?php echo CHtml::encode($this->pageTitle); ?></title>
</head>

<body>

<div class="container" id="page">

	<div id="header">
            <div id="logo"><img width='70' height='70' src='http://sisu.mx/development/kantorovich/AppInstaller/assets/img/sisu_logo_clear.png' /><text>App Installer</text></div>  
	</div><!-- header -->

	<div id="mainmenu">
		<?php
                    if(!Yii::app()->user->isGuest)
                    {
                    $this->widget('zii.widgets.CMenu',array(
			'items'=>array(
				array('label'=>'Home', 'url'=>array('/site/index')),
				array('label'=>'Nueva App', 'url'=>array('/aplicacion/create')),
                                array('label'=>'Admin Apps', 'url'=>array('/aplicacion/admin')),
				array('label'=>'Nuevos Usuarios', 'url'=>array('/usuario/createMany')),
                                array('label'=>'Admin Usuarios', 'url'=>array('/usuario/admin')),
				array('label'=>'Login', 'url'=>array('/site/login'), 'visible'=>Yii::app()->user->isGuest),
				array('label'=>'Logout ('.Yii::app()->user->name.')', 'url'=>array('/site/logout'), 'visible'=>!Yii::app()->user->isGuest)
			),
		)); 
                    }
                    
                    ?>
	</div><!-- mainmenu -->
	<?php if(isset($this->breadcrumbs)):?>
		<?php $this->widget('zii.widgets.CBreadcrumbs', array(
			'links'=>$this->breadcrumbs,
		)); ?><!-- breadcrumbs -->
	<?php endif?>

	<?php echo $content; ?>

	<div class="clear"></div>

	<div id="footer">
		Copyright &copy; <?php echo date('Y'); ?> by SISU Technologies.<br/>
		All Rights Reserved.<br/>
		<?php echo Yii::powered(); ?>
	</div><!-- footer -->

</div><!-- page -->

</body>
</html>