src/web/AppInstaller/protected/models/Aplicacion.php
<?php

/**
 * This is the model class for table "aplicaciones".
 *
 * The followings are the available columns in table 'aplicaciones':
 * @property integer $id
 * @property string $nombre
 * @property string $nombre_app
 * @property string $cliente
 *
 * The followings are the available model relations:
 * @property Usuarios[] $usuarios
 * @property Versiones[] $versiones
 */
class Aplicacion extends CActiveRecord
{
    
        
	public $img;
    
        /*
         * Behaviors/Comportamientos
         * 
         */
        public function behaviors(){
            return array('ESaveRelatedBehavior' => array( //SaveRelatedBehavior guarda relaciones 1:M o M:M
             'class' => 'application.components.ESaveRelatedBehavior')
         );
        }
        
        
	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return Aplicacion the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'aplicaciones';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('nombre, nombre_app', 'required'),
                        array('nombre_app', 'unique'),
			array('nombre, nombre_app, cliente', 'length', 'max'=>250),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, nombre, nombre_app, cliente', 'safe', 'on'=>'search'),
                        array('nombre_app', 'match', 'pattern'=>'/^[a-zA-Z0-9_]+$/', 'message'=>'El nombre corto del app solo puede tener caracteres o guiones bajos.'),
                        array('img', 'file', 'types'=>'png', 'allowEmpty'=>true, 'maxFiles'=>1, 'message'=>'Debe ser un archivo .png'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'usuarios' => array(self::MANY_MANY, 'Usuario', 'usuarios_aplicaciones(aplicacion_id, usuario_id)'),
			'versiones' => array(self::HAS_MANY, 'Version', 'aplicacion_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'nombre' => 'Nombre',
			'nombre_app' => 'Nombre corto App',
                        'img' => 'Subir Imagen',
                        'cliente' => 'Cliente',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('nombre',$this->nombre,true);
		$criteria->compare('nombre_app',$this->nombre_app,true);
                $criteria->compare('cliente',$this->cliente,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}
}

src/web/AppInstaller/protected/controllers/VersionController.php
<?php

class VersionController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update','createAppVer','UpdateAppVer','DeleteAppVer','File','index','view'),
				'users'=>array('developer@sisu.mx'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($aplicacion_id,$version)
	{
            $model = $this->loadModel($aplicacion_id,$version);
            $comms = Comentarios::model()->findAllByAttributes(array('version'=>$version,'aplicacion_id'=>$aplicacion_id));
            $fileDir = Yii::getPathOfAlias('files').'/'.$model->aplicacion->nombre_app.'/'.$model->version.'/'.$model->aplicacion->nombre_app;
            $root = Yii::getPathOfAlias('webroot').'/'.$fileDir;
            $model->apk=null;
            if(file_exists($root.'.apk'))
                    $model->apk=$model->aplicacion->nombre_app.'.apk';
            $model->ipa=null;
            if(file_exists($root.'.ipa'))
                    $model->ipa=$model->aplicacion->nombre_app.'.ipa';
            $model->plist=null;
            if(file_exists($root.'.plist'))
                    $model->plist=$model->aplicacion->nombre_app.'.plist';
                    
            
		$this->render('view',array(
			'model'=>$model,
                        'comms'=>$comms,
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Version;

		// Uncomment the following line if AJAX validation is needed
		$this->performAjaxValidation($model);

		if(isset($_POST['Version']))
		{
			$model->attributes=$_POST['Version'];
                        date_default_timezone_set("America/Mexico_City"); 
                        if(!$model->fecha_version)
                            $model->fecha_version=date('Y-m-d H:i:s');
			if($model->save())
                        {
                            $this->updateVersionFiles($model);
                            $push = new PushNotificationManager();
                            $push->sendPushForApp("Version ".$model->version." de ".$model->aplicacion->nombre." esta lista!",$model->aplicacion);
                            $this->redirect(array('view','aplicacion_id'=>$model->aplicacion_id,'version'=>$model->version));
                        }
				
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}
        
        /**
	 * Crear version desde view de aplicacion
	 * 
	 */
	public function actionCreateAppVer($aplicacion_id)
	{
		$model=new Version;
                $model->aplicacion_id=$aplicacion_id;

		// Uncomment the following line if AJAX validation is needed
		$this->performAjaxValidation($model);

		if(isset($_POST['Version']))
		{
			$model->attributes=$_POST['Version'];
                        date_default_timezone_set("America/Mexico_City"); 
                        if(!$model->fecha_version)
                            $model->fecha_version=date('Y-m-d H:i:s');
			if($model->save())
                        {
                            $this->updateVersionFiles($model);
                            $push = new PushNotificationManager();
                            $push->sendPushForApp("Version ".$model->version." de ".$model->aplicacion->nombre." esta lista!",$model->aplicacion);
                            $this->redirect(array('aplicacion/view','id'=>$model->aplicacion_id));
                        }
				
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($aplicacion_id,$version)
	{
		$model=$this->loadModel($aplicacion_id,$version);

		// Uncomment the following line if AJAX validation is needed
		$this->performAjaxValidation($model);

		if(isset($_POST['Version']))
		{
			$model->attributes=$_POST['Version'];
			if($model->save()){
                            $this->updateVersionFiles($model);
                            $this->redirect(array('view','aplicacion_id'=>$model->aplicacion_id,'version'=>$model->version));
                        }
				
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}
        
        /**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdateAppVer($aplicacion_id,$version)
	{
		$model=$this->loadModel($aplicacion_id,$version);

		// Uncomment the following line if AJAX validation is needed
		$this->performAjaxValidation($model);

		if(isset($_POST['Version']))
		{
			$model->attributes=$_POST['Version'];
			if($model->save()){
                            $this->updateVersionFiles($model);
                            $this->redirect(array('aplicacion/view','id'=>$model->aplicacion_id));
                        }
				
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($aplicacion_id,$version)
	{
		$model = $this->loadModel($aplicacion_id,$version);
                
                $aplicacion = Aplicacion::model()->findByPk($model->aplicacion_id);
                
                $dir = Yii::getPathOfAlias('webroot').Yii::getPathOfAlias('files').'/'.$aplicacion->nombre_app.'/'.$model->version;
                
                $model->delete();
                
                if(file_exists($dir))
                {
                    function rrmdir($dir) 
                    { 
                      foreach(glob($dir . '/*') as $file) 
                      { 
                        if(is_dir($file)) rrmdir($file); else unlink($file); 
                      } rmdir($dir); 
                    }
                    rrmdir($dir);
                }

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('index'));
	}
        
        /**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDeleteAppVer($aplicacion_id,$version)
	{
		$model = $this->loadModel($aplicacion_id,$version);
                
                $aplicacion = Aplicacion::model()->findByPk($model->aplicacion_id);
                
                $dir = Yii::getPathOfAlias('webroot').Yii::getPathOfAlias('files').'/'.$aplicacion->nombre_app.'/'.$model->version;
                
                $model->delete();
                
                if(file_exists($dir))
                {
                    function rrmdir($dir) 
                    { 
                      foreach(glob($dir . '/*') as $file) 
                      { 
                        if(is_dir($file)) rrmdir($file); else unlink($file); 
                      } rmdir($dir); 
                    }
                    rrmdir($dir);
                }

		$this->redirect(array('aplicacion/view','id'=>$model->aplicacion_id));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Version');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}
        
        
        /**
	 * Regresa el archivo
	 */
	public function actionFile($aplicacion_id,$version,$tipo)
	{
            $model = $this->loadModel($aplicacion_id,$version);
            $fileDir = Yii::getPathOfAlias('files').'/'.$model->aplicacion->nombre_app.'/'.$model->version.'/'.$model->aplicacion->nombre_app;
            $root = Yii::getPathOfAlias('webroot').'/'.$fileDir;
            /*Yii::app()->request->xSendFile($root.'.'.$tipo,array(
                //'saveName'=>'RequestedFile.jpg',
                'terminate'=>false,
             ));*/
            Yii::app()->request->sendFile($model->aplicacion->nombre_app.'.'.$tipo,file_get_contents($root.'.'.$tipo),null,false);
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Version('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Version']))
			$model->attributes=$_GET['Version'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Version the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($aplicacion_id,$version)
	{
		$model=Version::model()->findByPk(array('aplicacion_id' => $aplicacion_id, 'version' => $version));
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Version $model the model to be validated
	 */

src/web/AppInstaller/protected/views/aplicacion/_form.php
<?php
/* @var $this AplicacionController */
/* @var $model Aplicacion */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'aplicacion-form',
	'enableAjaxValidation'=>true,
        'htmlOptions' => array('enctype' => 'multipart/form-data'),
)); ?>

	<p class="note">Campos con <span class="required">*</span> son necesarios.</p>

	<?php echo $form->errorSummary(array($model,$version)); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'nombre'); ?>
		<?php echo $form->textField($model,'nombre',array('size'=>60,'maxlength'=>250)); ?>
		<?php echo $form->error($model,'nombre'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'nombre_app'); ?>
		<?php echo $form->textField($model,'nombre_app',array('size'=>60,'maxlength'=>250)); ?>
		<?php echo $form->error($model,'nombre_app'); ?>
	</div>
        
        <div class="row">
		<?php echo $form->labelEx($model,'cliente'); ?>
		<?php echo $form->textField($model,'cliente',array('size'=>60,'maxlength'=>250)); ?>
		<?php echo $form->error($model,'cliente'); ?>
	</div>
        
        <div class="row">
		<?php echo $form->labelEx($model,'img'); ?>
		<?php echo $form->fileField($model,'img',array('accept'=>"image/x-png")); ?>
		<?php echo $form->error($model,'img'); ?>
	</div>
        <br>
        Agregar usuarios:
        <div class="row">
            <?php  
                $data = array();
                $usrs = array();
                 foreach(Usuario::model()->findAll() as $usr){
                    $usrs[$usr->id] = $usr->nombre.' '.$usr->apellido;
                }
                echo Chosen::multiSelect('Usuarios',$data , $usrs,array('style'=>'width:100%'));
            ?>
        </div>
        
        <br><br><h2>Primera version</h2>

	<div class="row">
		<?php echo $form->labelEx($version,'version'); ?>
		<?php echo $form->textField($version,'version',array('size'=>60,'maxlength'=>250)); ?>
		<?php echo $form->error($version,'version'); ?>
	</div>
        
        <div class="row">
		<?php echo $form->labelEx($version,'apk'); ?>
		<?php echo $form->fileField($version,'apk',array('size'=>60,'maxlength'=>250)); ?>
		<?php echo $form->error($version,'apk'); ?>
	</div>
        
        <div class="row">
		<?php echo $form->labelEx($version,'ipa'); ?>
		<?php echo $form->fileField($version,'ipa',array('size'=>60,'maxlength'=>250)); ?>
		<?php echo $form->error($version,'ipa'); ?>
	</div>
        
        <div class="row">
		<?php echo $form->labelEx($version,'plist'); ?>
		<?php echo $form->fileField($version,'plist',array('size'=>60,'maxlength'=>250)); ?>
		<?php echo $form->error($version,'plist'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($version,'notas'); ?>
		<?php echo $form->textArea($version,'notas'); ?>
		<?php echo $form->error($version,'notas'); ?>
	</div>

        

	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Crear' : 'Guardar'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

src/web/AppInstaller/protected/views/aplicacion/_search.php
<?php
/* @var $this AplicacionController */
/* @var $model Aplicacion */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'nombre'); ?>
		<?php echo $form->textField($model,'nombre',array('size'=>60,'maxlength'=>250)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'nombre_app'); ?>
		<?php echo $form->textField($model,'nombre_app',array('size'=>60,'maxlength'=>250)); ?>
	</div>
    
        <div class="row">
		<?php echo $form->label($model,'cliente'); ?>
		<?php echo $form->textField($model,'cliente',array('size'=>60,'maxlength'=>250)); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

src/web/AppInstaller/protected/views/aplicacion/_view.php
<?php
/* @var $this AplicacionController */
/* @var $data Aplicacion */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('nombre')); ?>:</b>
	<?php echo CHtml::encode($data->nombre); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('nombre_app')); ?>:</b>
	<?php echo CHtml::encode($data->nombre_app); ?>
	<br />
        
        <b><?php echo CHtml::encode($data->getAttributeLabel('cliente')); ?>:</b>
	<?php echo CHtml::encode($data->cliente); ?>
	<br />


</div>

src/web/AppInstaller/protected/views/aplicacion/admin.php
<?php
/* @var $this AplicacionController */
/* @var $model Aplicacion */

$this->breadcrumbs=array(
	'Aplicaciones',
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#aplicacion-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Administrador de Aplicaciones</h1>

<p>
You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'aplicacion-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		'nombre',
		'nombre_app',
                'cliente',
		array(
			'class'=>'CButtonColumn',
		),
	),
)); ?>

src/web/AppInstaller/protected/views/aplicacion/create.php
<?php
    /* @var $this AplicacionController */
    /* @var $model Aplicacion */

    $this->breadcrumbs=array(
            'Aplicaciones'=>array('index'),
            'Crear Nueva',
    );
?>

<h1>Create Aplicacion</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model,'version'=>$version)); ?>

src/web/AppInstaller/protected/views/aplicacion/editar.php
<?php
/* @var $this AplicacionController */
/* @var $model Aplicacion */
/* @var $form CActiveForm */


?>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'aplicacion-editar-form',
	'enableAjaxValidation'=>false,
)); ?>

	<p class="note">Campos con <span class="required">*</span> son necesarios.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'nombre'); ?>
		<?php echo $form->textField($model,'nombre',array('size'=>60,'maxlength'=>250)); ?>
		<?php echo $form->error($model,'nombre'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'nombre_app'); ?>
		<?php echo $form->textField($model,'nombre_app',array('size'=>60,'maxlength'=>250)); ?>
		<?php echo $form->error($model,'nombre_app'); ?>
	</div>
        
        <div class="row">
		<?php echo $form->labelEx($model,'cliente'); ?>
		<?php echo $form->textField($model,'cliente',array('size'=>60,'maxlength'=>250)); ?>
		<?php echo $form->error($model,'cliente'); ?>
	</div>
        
        <div class="row">
		<?php echo $form->labelEx($model,'img'); ?>
		<?php echo $form->fileField($model,'img'); ?>
		<?php echo $form->error($model,'img'); ?>
	</div>


	<div class="row buttons">
		<?php echo CHtml::submitButton('Guardar'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

src/web/AppInstaller/protected/views/aplicacion/update.php
<?php
/* @var $this AplicacionController */
/* @var $model Aplicacion */

$this->breadcrumbs=array(
        'Aplicaciones'=>array('aplicacion/admin'),
	$model->nombre_app=>array('aplicacion/view','id'=>$model->id),
	'Editar',
);

?>

<h1>Editar app <?php echo $model->nombre; ?></h1>

<?php echo $this->renderPartial('editar', array('model'=>$model)); ?>

src/web/AppInstaller/protected/views/aplicacion/view.php
<?php
/* @var $this AplicacionController */
/* @var $model Aplicacion */

$this->breadcrumbs=array(
	'Aplicaciones'=>array('index'),
	$model->nombre_app,
);
?>

<h1>
    <?php 
        echo "<img width='100' height='100' src='http://sisu.mx/development/kantorovich/AppInstaller/index.php/rest/556391-9555/img/".$model->id."' />"
    ?>

    App <?php echo $model->nombre; ?>
</h1>

<?php echo CHtml::link(CHtml::button('Editar app'),array('update','id'=>$model->id),array('style'=>'float:right;')); ?>
<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'nombre_app',
                'cliente',
	),
)); ?>

<?php
$columns = array('Ver','Version','Fecha','Editar','Borrar');
$rows = array();
foreach($model->versiones as $version){
    $arr = array(
        CHtml::link(CHtml::image("../../assets/img/view.png"),array('version/view','aplicacion_id'=>$model->id,'version'=>$version->version)),
        $version->version,
        $version->fecha_version,
        CHtml::link(CHtml::image("../../assets/img/edit.png"),array('version/updateAppVer','aplicacion_id'=>$model->id,'version'=>$version->version)),
        CHtml::link(CHtml::image("../../assets/img/delete.png"),array('version/deleteAppVer','aplicacion_id'=>$model->id,'version'=>$version->version)),
        );
    array_push($rows,$arr);
}

$this->widget('htmlTableUi',array(
    'ajaxUrl'=>'site/handleHtmlTable',
    'arProvider'=>'',    
    'collapsed'=>false,
    'columns'=>$columns,
    'cssFile'=>'',
    'editable'=>false,
    'enableSort'=>true,
    'rows'=>$rows,
    'sortColumn'=>1,
    'sortOrder'=>'asc',
    'title'=>'Versiones',
));
?>

<div class="row buttons">
		<?php echo CHtml::link(CHtml::button('Nueva version'),array('version/CreateAppVer','aplicacion_id'=>$model->id)); ?>   
</div>
<br>
Usuarios:
<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'aplicacion-form',
	'enableAjaxValidation'=>true,
)); ?>
<div class="row">
    <?php  
        $data = array();
        foreach($model->usuarios as $usr){
            array_push($data,$usr->id);
        }
        $usrs = array() ;
         foreach(Usuario::model()->findAll() as $usr){
            $usrs[$usr->id] = $usr->nombre.' '.$usr->apellido;
        }
        echo Chosen::multiSelect('Usuarios',$data , $usrs,array('style'=>'width:100%'));
        echo CHtml::submitButton('Guardar cambios');
    
    ?>
</div>

<?php $this->endWidget(); ?>
<br>
<br>
<div class="row" style='float:right'>
    <?php echo CHtml::link(CHtml::button('Borrar app'),"#",array('submit'=>array('delete','id'=>$model->id),'confirm'=>'¿Seguro que deseas borrar el app '.$model->nombre.'?'),array('style'=>'float:right')); ?>
</div>