src/web/AppInstaller/protected/models/Version.php
<?php

/**
 * This is the model class for table "versiones".
 *
 * The followings are the available columns in table 'versiones':
 * @property integer $aplicacion_id
 * @property string $version
 * @property string $notas
 * @property string $fecha_version
 *
 * The followings are the available model relations:
 * @property Aplicacion $aplicacion
 */
class Version extends CActiveRecord
{
    
        public $apk;
	public $ipa;
	public $plist;
	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return Version the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'versiones';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('aplicacion_id, version, notas', 'required'),
			array('aplicacion_id', 'numerical', 'integerOnly'=>true),
			array('version', 'length', 'max'=>250),
                        array('version', 'UniqueAttributesValidator', 'with'=>'aplicacion_id'),
			array('notas', 'length', 'max'=>500),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('aplicacion_id, version, notas, fecha_version', 'safe', 'on'=>'search'),
                        array('version', 'match', 'pattern'=>'/^[a-zA-Z0-9_.]+$/', 'message'=>'La version solo puede contener caracteres alfanumericos, punto y guion bajo.'),
                        array('apk', 'file', 'types'=>'apk,', 'allowEmpty'=>true, 'maxFiles'=>1, 'message'=>'Debe ser un archivo .apk'),
                        array('ipa', 'file', 'types'=>'ipa,', 'allowEmpty'=>true, 'maxFiles'=>1, 'message'=>'Debe ser un archivo .ipa'),
                        array('plist', 'file', 'types'=>'plist,', 'allowEmpty'=>true, 'maxFiles'=>1, 'message'=>'Debe ser un archivo .plist'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'aplicacion' => array(self::BELONGS_TO, 'Aplicacion', 'aplicacion_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'aplicacion_id' => 'Aplicacion',
			'version' => 'Version',
			'notas' => 'Notas',
			'fecha_version' => 'Fecha Version',
                        'apk' => 'Subir APK',
                        'ipa' => 'Subir IPA',
                        'plist' => 'Subir PLIST',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('aplicacion_id',$this->aplicacion_id);
		$criteria->compare('version',$this->version,true);
		$criteria->compare('notas',$this->notas,true);
		$criteria->compare('fecha_version',$this->fecha_version,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}
        
        
}

src/web/AppInstaller/protected/controllers/VersionController.php
<?php

class VersionController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update','createAppVer','UpdateAppVer','DeleteAppVer','File','index','view'),
				'users'=>array('developer@sisu.mx'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($aplicacion_id,$version)
	{
            $model = $this->loadModel($aplicacion_id,$version);
            $comms = Comentarios::model()->findAllByAttributes(array('version'=>$version,'aplicacion_id'=>$aplicacion_id));
            $fileDir = Yii::getPathOfAlias('files').'/'.$model->aplicacion->nombre_app.'/'.$model->version.'/'.$model->aplicacion->nombre_app;
            $root = Yii::getPathOfAlias('webroot').'/'.$fileDir;
            $model->apk=null;
            if(file_exists($root.'.apk'))
                    $model->apk=$model->aplicacion->nombre_app.'.apk';
            $model->ipa=null;
            if(file_exists($root.'.ipa'))
                    $model->ipa=$model->aplicacion->nombre_app.'.ipa';
            $model->plist=null;
            if(file_exists($root.'.plist'))
                    $model->plist=$model->aplicacion->nombre_app.'.plist';
                    
            
		$this->render('view',array(
			'model'=>$model,
                        'comms'=>$comms,
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Version;

		// Uncomment the following line if AJAX validation is needed
		$this->performAjaxValidation($model);

		if(isset($_POST['Version']))
		{
			$model->attributes=$_POST['Version'];
                        date_default_timezone_set("America/Mexico_City"); 
                        if(!$model->fecha_version)
                            $model->fecha_version=date('Y-m-d H:i:s');
			if($model->save())
                        {
                            $this->updateVersionFiles($model);
                            $push = new PushNotificationManager();
                            $push->sendPushForApp("Version ".$model->version." de ".$model->aplicacion->nombre." esta lista!",$model->aplicacion);
                            $this->redirect(array('view','aplicacion_id'=>$model->aplicacion_id,'version'=>$model->version));
                        }
				
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}
        
        /**
	 * Crear version desde view de aplicacion
	 * 
	 */
	public function actionCreateAppVer($aplicacion_id)
	{
		$model=new Version;
                $model->aplicacion_id=$aplicacion_id;

		// Uncomment the following line if AJAX validation is needed
		$this->performAjaxValidation($model);

		if(isset($_POST['Version']))
		{
			$model->attributes=$_POST['Version'];
                        date_default_timezone_set("America/Mexico_City"); 
                        if(!$model->fecha_version)
                            $model->fecha_version=date('Y-m-d H:i:s');
			if($model->save())
                        {
                            $this->updateVersionFiles($model);
                            $push = new PushNotificationManager();
                            $push->sendPushForApp("Version ".$model->version." de ".$model->aplicacion->nombre." esta lista!",$model->aplicacion);
                            $this->redirect(array('aplicacion/view','id'=>$model->aplicacion_id));
                        }
				
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($aplicacion_id,$version)
	{
		$model=$this->loadModel($aplicacion_id,$version);

		// Uncomment the following line if AJAX validation is needed
		$this->performAjaxValidation($model);

		if(isset($_POST['Version']))
		{
			$model->attributes=$_POST['Version'];
			if($model->save()){
                            $this->updateVersionFiles($model);
                            $this->redirect(array('view','aplicacion_id'=>$model->aplicacion_id,'version'=>$model->version));
                        }
				
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}
        
        /**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdateAppVer($aplicacion_id,$version)
	{
		$model=$this->loadModel($aplicacion_id,$version);

		// Uncomment the following line if AJAX validation is needed
		$this->performAjaxValidation($model);

		if(isset($_POST['Version']))
		{
			$model->attributes=$_POST['Version'];
			if($model->save()){
                            $this->updateVersionFiles($model);
                            $this->redirect(array('aplicacion/view','id'=>$model->aplicacion_id));
                        }
				
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($aplicacion_id,$version)
	{
		$model = $this->loadModel($aplicacion_id,$version);
                
                $aplicacion = Aplicacion::model()->findByPk($model->aplicacion_id);
                
                $dir = Yii::getPathOfAlias('webroot').Yii::getPathOfAlias('files').'/'.$aplicacion->nombre_app.'/'.$model->version;
                
                $model->delete();
                
                if(file_exists($dir))
                {
                    function rrmdir($dir) 
                    { 
                      foreach(glob($dir . '/*') as $file) 
                      { 
                        if(is_dir($file)) rrmdir($file); else unlink($file); 
                      } rmdir($dir); 
                    }
                    rrmdir($dir);
                }

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('index'));
	}
        
        /**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDeleteAppVer($aplicacion_id,$version)
	{
		$model = $this->loadModel($aplicacion_id,$version);
                
                $aplicacion = Aplicacion::model()->findByPk($model->aplicacion_id);
                
                $dir = Yii::getPathOfAlias('webroot').Yii::getPathOfAlias('files').'/'.$aplicacion->nombre_app.'/'.$model->version;
                
                $model->delete();
                
                if(file_exists($dir))
                {
                    function rrmdir($dir) 
                    { 
                      foreach(glob($dir . '/*') as $file) 
                      { 
                        if(is_dir($file)) rrmdir($file); else unlink($file); 
                      } rmdir($dir); 
                    }
                    rrmdir($dir);
                }

		$this->redirect(array('aplicacion/view','id'=>$model->aplicacion_id));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Version');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}
        
        
        /**
	 * Regresa el archivo
	 */
	public function actionFile($aplicacion_id,$version,$tipo)
	{
            $model = $this->loadModel($aplicacion_id,$version);
            $fileDir = Yii::getPathOfAlias('files').'/'.$model->aplicacion->nombre_app.'/'.$model->version.'/'.$model->aplicacion->nombre_app;
            $root = Yii::getPathOfAlias('webroot').'/'.$fileDir;
            /*Yii::app()->request->xSendFile($root.'.'.$tipo,array(
                //'saveName'=>'RequestedFile.jpg',
                'terminate'=>false,
             ));*/
            Yii::app()->request->sendFile($model->aplicacion->nombre_app.'.'.$tipo,file_get_contents($root.'.'.$tipo),null,false);
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Version('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Version']))
			$model->attributes=$_GET['Version'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Version the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($aplicacion_id,$version)
	{
		$model=Version::model()->findByPk(array('aplicacion_id' => $aplicacion_id, 'version' => $version));
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Version $model the model to be validated
	 */

src/web/AppInstaller/protected/views/version/_form.php
<?php
/* @var $this VersionController */
/* @var $model Version */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'version-form',
	'enableAjaxValidation'=>true,
        'htmlOptions' => array('enctype' => 'multipart/form-data'),
)); ?>

	<p class="note">Campos con <span class="required">*</span> son necesarios.</p>

	<?php echo $form->errorSummary($model); ?>
        
        <div class="row">
                <?php 
                    echo $form->labelEx($model,'aplicacion_id');
                    echo '<br>';
                    /*
                    $models=Aplicacion::model()->findAll();
                    $Data=array();
                    foreach($models as $model2)
                    {
                        $Data[$model2->id]=$model2->nombre;
                    }
                    echo $form->dropDownList($model,'aplicacion_id',$Data);
                    echo $form->error($model,'aplicacion_id'); 
                     *
                     */
                    echo $model->aplicacion->nombre;
                ?>
            <br><br>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'version'); ?>
		<?php echo $form->textField($model,'version',array('size'=>60,'maxlength'=>250)); ?>
		<?php echo $form->error($model,'version'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'notas'); ?>
		<?php echo $form->textArea($model,'notas',array('size'=>60,'maxlength'=>500)); ?>
		<?php echo $form->error($model,'notas'); ?>
	</div>
        <br>
        <?php 
            if(!$model->isNewRecord)
                echo 'Actualizar alguno de estos archivos sobreescribira el existente en esta versión.';
        ?>
        <br>
        <div class="row">
		<?php echo $form->labelEx($model,'apk'); ?>
		<?php echo $form->fileField($model,'apk',array('size'=>60,'maxlength'=>250)); ?>
		<?php echo $form->error($model,'apk'); ?>
	</div>
        
        <div class="row">
		<?php echo $form->labelEx($model,'ipa'); ?>
		<?php echo $form->fileField($model,'ipa',array('size'=>60,'maxlength'=>250)); ?>
		<?php echo $form->error($model,'ipa'); ?>
	</div>
        
        <div class="row">
		<?php echo $form->labelEx($model,'plist'); ?>
		<?php echo $form->fileField($model,'plist',array('size'=>60,'maxlength'=>250)); ?>
		<?php echo $form->error($model,'plist'); ?>
	</div>
        <br>
	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Crear' : 'Guardar'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

src/web/AppInstaller/protected/views/version/_search.php
<?php
/* @var $this VersionController */
/* @var $model Version */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>


	<div class="row">
		<?php echo $form->label($model,'aplicacion_id'); ?>
		<?php echo $form->textField($model,'aplicacion_id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'version'); ?>
		<?php echo $form->textField($model,'version',array('size'=>60,'maxlength'=>250)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'notas'); ?>
		<?php echo $form->textField($model,'notas',array('size'=>60,'maxlength'=>500)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'fecha_version'); ?>
		<?php echo $form->textField($model,'fecha_version'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

src/web/AppInstaller/protected/views/version/_view.php
<?php
/* @var $this VersionController */
/* @var $data Version */
?>

<div class="view">


        <b><?php echo CHtml::encode($data->getAttributeLabel('version')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->version), array('view', 'aplicacion_id'=>$data->aplicacion_id,'version'=>$data->version)); ?>
	<br />
        
	<b><?php echo CHtml::encode($data->getAttributeLabel('aplicacion_id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->aplicacion->nombre_app), array('aplicacion/view', 'id'=>$data->aplicacion_id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('notas')); ?>:</b>
	<?php echo CHtml::encode($data->notas); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('fecha_version')); ?>:</b>
	<?php echo CHtml::encode($data->fecha_version); ?>
	<br />


</div>

src/web/AppInstaller/protected/views/version/comentario_view.php
<?php
/* @var $comment Comentarios*/
?>

<div class="view">


        <b><?php echo CHtml::encode($comment->getAttributeLabel('usuario_id')); ?>:</b>
	<?php echo CHtml::encode($comment->usuario->nombre.' '.$comment->usuario->apellido); ?>
	<br />
        
        <b><?php echo CHtml::encode($comment->getAttributeLabel('plataforma')); ?>:</b>
	<?php echo CHtml::encode(($comment->plataforma==1?'Android':'iOS')); ?>
	<br />
        
	<b><?php echo CHtml::encode($comment->getAttributeLabel('fecha')); ?>:</b>
	<?php echo CHtml::encode($comment->fecha); ?>
	<br />

	<b><?php echo CHtml::encode($comment->getAttributeLabel('comentario')); ?>:</b>
	<?php echo CHtml::encode($comment->comentario); ?>
	<br />


</div>

src/web/AppInstaller/protected/views/version/create.php
<?php
/* @var $this VersionController */
/* @var $model Version */

$this->breadcrumbs=array(
        'Aplicaciones'=>array('aplicacion/admin'),
	$model->aplicacion->nombre_app=>array('aplicacion/view','id'=>$model->aplicacion_id),
	'CrearVersion',
);
?>

<h1>Nueva Version</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

src/web/AppInstaller/protected/views/version/update.php
<?php
/* @var $this VersionController */
/* @var $model Version */

$this->breadcrumbs=array(
        'Aplicaciones'=>array('aplicacion/admin'),
	$model->aplicacion->nombre_app=>array('aplicacion/view','id'=>$model->aplicacion_id),
	'Update version',
);
?>

<h1>Editar versión <?php echo $model->aplicacion->nombre_app.' '.$model->version ?></h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

src/web/AppInstaller/protected/views/version/view.php
<?php
/* @var $this VersionController */
/* @var $model Version */
/* @var $comms Comentarioss */

$this->breadcrumbs=array(
        'Aplicaciones'=>array('aplicacion/admin'),
	$model->aplicacion->nombre_app=>array('aplicacion/view','id'=>$model->aplicacion_id),
	'Version '.$model->version,
);
?>

<h1>View Version <?php echo $model->aplicacion->nombre_app.' '.$model->version; ?></h1>

<?php 

$atributos = array(
    'version',
    array('label'=>'aplication_id','type'=>'raw','value'=>CHtml::link(CHtml::encode($model->aplicacion->nombre_app), array('aplicacion/view', 'id'=>$model->aplicacion_id))),
    'notas',
    'fecha_version',
);

if($model->apk != null)
    array_push($atributos,array('label'=>'apk','type'=>'raw','value'=>CHtml::link(CHtml::encode($model->apk), array('version/file', 'aplicacion_id'=>$model->aplicacion_id,'version'=>$model->version, 'tipo'=>'apk'))));
if($model->ipa != null)
    array_push($atributos,array('label'=>'ipa','type'=>'raw','value'=>CHtml::link(CHtml::encode($model->ipa), array('version/file', 'aplicacion_id'=>$model->aplicacion_id,'version'=>$model->version, 'tipo'=>'ipa'))));
if($model->plist != null)
    array_push($atributos,array('label'=>'plist','type'=>'raw','value'=>CHtml::link(CHtml::encode($model->plist), array('version/file', 'aplicacion_id'=>$model->aplicacion_id,'version'=>$model->version, 'tipo'=>'plist'))));


$this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>$atributos,
)); 

?>
<br><br>
Comentarios:
<?php


    foreach($comms as $comment){
        echo $this->renderPartial('comentario_view', array('comment'=>$comment));
    }


?>